apiVersion: v1
kind: Service
metadata:
  name: nginx-deploy-srv
  labels: 
    name: rs-label
    type: back-end
spec:
  type: NodePort
  selector:
    name:  rs-label
    type: back-end
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31010  

