apiVersion: v1
kind: Pod
metadata:
  name: with0node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/e2e-az-name
          operator: In
          values:
          - e2e-az1
          - e2e-az2
      preferredDut=ringSchedulingIgnoredDurinfExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: node-label-key
            operator: In
            values:
            - node-label-value
  containers:
  - name: with-node-affinity
    image: k8.gcr.io/pause:2.0

