apiVersion: v1
kind: Pod
metadata:
  name: mai-nginx
  labels:
    env: test1
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  priorityClassName: high-priority
