apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels: 
    name: rs-label
    type: back-end
spec:
  template: 
    
    metadata: 
      name: nginx
      labels: 
        name: rs-label
        type: back-end

    spec: 
      containers:
        - name: nginx-demo
          image: nginx:1.17
  replicas: 3
  selector:
    matchLabels:
      name: rs-label
      type: back-end
