apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets-mai
  namespace: development
subjects:
- kind: User
  name: mai
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: secret-reader-mai
  apiGroup: rbac.authorization.k8s.io

