apiVersion: v1
kind: Pod
metadata:
  name: secret-test-prod-mai
  labels:
    name: secret-test
spec:
  volumes:
  - name: maithvol1
    secret:
      secretName: ssh-key-secret-mai
  containers:
  - name: ssh-test-container
    image: httpd
    volumeMounts:
    - name: maithvol1
      readOnly: true
      mountPath: "/etc/secret-volume"

